### ISSUE TITLE
Remove Overlap From Right Side of Floating Bar

### ISSUE THREAD

**Issue by nms808** [anaarkei/zen-floating-findbar#1]
I just discovered this extenstion in the Zen Store, very nice! Is it possible to clean up the right side and shorten the floating bar so it sits inside the scroll bar, entirely in the web view with a small gap just like on the left? The last few updates moved things around again so it may have caused this misalignment. Some of the other plugins in the Zen Store have been made useless now, others need to be updated, and some of them were made redundant...but not this one! 👍 

Thank you!

![Floating Bar Left Side](https://github.com/user-attachments/assets/fa461bc4-98e7-42e7-93e7-c4fafc95081a)
![Floating Bar Right Side Overlap](https://github.com/user-attachments/assets/98c9f4f7-df0f-436a-9042-3ea43ca3a627)

**Comment by nms808** [comment]
Forgot to mention, you may need to increase the gap, shorten the bar, on the left also so that it will be uniform when the scroll bar is not active. 💯 Just noticed that the compact mode is also off center in the web view pane.

**Comment by anaarkei** [comment]
> Forgot to mention, you may need to increase the gap, shorten the bar, on the left also so that it will be uniform when the scroll bar is not active. 💯 Just noticed that the compact mode is also off center in the web view pane.

Compact mode has been fixed in the latest version of this mod.

**Comment by nms808** [comment]
Just thought I'd mention the Zen Store is still serving up version 1.0.0 so that needs an updated link as well. Thank you for the update!
